// console.log(
//     "started"
// );

// // const a = getValue1();/
// let a;
// try{
//     console.log('on try');
// a= getValue1();
// }catch(e){
//     a=0;
// }

// const b = getValue2();
// const result = processValue(a,b);
// console.log(result);


// console.log('ended');

// ///////////////////////////////////////////////

// function getValue1(){
// //   junk()
// console.log('inside getValue1');
//     return 12;
  
// }
// function getValue2(){
//     return 22;
// }

// function processValue(){
//     return a+b;
// }



if (someConditionIsNotMet) {
    throw new Error('This is a custom error message');
  }
  